=== wynddao/wyndex-ui/mock/schema/pair.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "apr": {
      "type": "number"
    },
    "liquidity": {
      "type": "string"
    },
    "fee": {
      "type": "number"
    },
    "tokens": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "tokenType": {
              "type": "string"
            },
            "img": {
              "type": "string"
            },
            "denom": {
              "type": "string"
            },
            "decimals": {
              "type": "integer"
            },
            "chain": {
              "type": "string"
            }
          },
          "required": ["name", "tokenType", "img", "denom", "decimals", "chain"]
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "tokenType": {
              "type": "string"
            },
            "contractAddress": {
              "type": "string"
            },
            "img": {
              "type": "string"
            },
            "denom": {
              "type": "string"
            },
            "decimals": {
              "type": "integer"
            },
            "chain": {
              "type": "string"
            }
          },
          "required": ["name", "tokenType", "contractAddress", "img", "denom", "decimals", "chain"]
        }
      ]
    }
  },
  "required": ["id", "apr", "liquidity", "fee", "tokens"]
}

=== wynddao/wyndex-ui/mock/pair/1.json
{
  "id": 1,
  "apr": 0.5,
  "liquidity": "100000",
  "fee": 0.002,
  "tokens": [
    {
      "name": "JUNOX",
      "tokenType": "native",
      "img": "https://app.osmosis.zone/_next/image?url=%2Ftokens%2Fjuno.svg&w=64&q=75",
      "denom": "ujunox",
      "decimals": 6,
      "chain": "junotestnet"
    },
    {
      "name": "WYND",
      "tokenType": "cw20",
      "contractAddress": "juno1q56cfjewxp2f0pqtrpyx78j55zfxnz4z27y6fayew0wqw9m2t87sjfgf54",
      "img": "https://app.wynddao.com/image.png",
      "denom": "uwynd",
      "decimals": 6,
      "chain": "junotestnet"
    }
  ]
}
